[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
    ]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options



# profile for Base mainnet forking
[profile.base_fork]
# Inherit from default profile
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 10000
via_ir = true

# Replace with your actual Base Mainnet RPC URL
fork_url = "YOUR_BASE_MAINNET_RPC_URL_HERE"
# Optional: Specify a block number to fork from for consistent tests
fork_block_number = 30483478 

# Optional: Increase verbosity for tests (vv, vvv, vvvv)
# verbosity = 2

# Optional: If you want to use this profile by default for `forge test`
# [rpc_endpoints]
# base = "https://mainnet.base.org"

# [profile.default.fuzz] # Default fuzz settings
# runs = 256

# forge test --fork-url "https://mainnet.base.org" --fork-block-number 30483478 -vvv